mintel/build-harness-extensions

modules/kubecfg/Makefile
modules/opa/Makefile
modules/pluto/Makefile
modules/tanka/Makefile

* Use `find` instead of `ls` to make jobs more flexible for multi-level environments

Tanka Fixes

---

README.md
modules/alembic/Makefile
modules/pipenv/Makefile
modules/poetry/Makefile
modules/pytest/Makefile
modules/python/Makefile
modules/python/Makefile.autoflake
modules/python/Makefile.black
modules/python/Makefile.flake8
modules/python/Makefile.isort
modules/python/Makefile.lint
modules/python/Makefile.mypy

Python, alembic, pytest, autoflake, flake8, black, isort, mypy and poetry helpers

Python modules

---

modules/asdf/Makefile
modules/jsonnet/Makefile
modules/kind/Makefile
modules/kubecfg/Makefile
modules/kubeval/Makefile
modules/opa/Makefile
modules/pluto/Makefile
modules/satoshi/Makefile
modules/tanka/Makefile

- Validate that binaries are installed for most of the tanka/jsonnet related projects
- Added PHONY (none of these are files on disk...)

Adding satoshi/check-deps target

---

modules/docker/Makefile.registry
modules/gitlab/Makefile.registry

Helpers for Docker and Gitlab registry authentication.

Docker and Gitlab modules

---

modules/tanka/generate.sh

This change supports both individual and multiple-named environments, even within the same repo

Add support for multiple inline environments to tanka module

---

modules/satoshi/tool-versions

We mostly need kubectl updated, but these other updates seem harmless.

Update tool versions

---

modules/satoshi/tool-versions

Adding `helm-docs` (tool for auto-building the helm-chart `README.md`)

Adding helm-docs to satoshi asdf tool-versions.

---

modules/k8s/tanka/generate.sh

For a single file that generates multiple environments ([example](https://gitlab.com/mintel/satoshi/kubernetes/jsonnet/sre/monitoring-cluster-jsonnet/-/blob/main/environments/prometheus-yace-exporter/aws.prod/main.jsonnet)) `generate` will currently fail because it's looking for a path that doesn't exist (`environments/prometheus-yace-exporter/aws.prod/eu-prod1` in this example). This change will search backwards from the provided path until it finds the folder containing the jsonnet file(s).

Fix paths for generated envs

---

modules/k8s/tanka/generate.sh

feat: Add ability to name rendered files via an annotation if needed

Terraform Cloud:

---

modules/k8s/Makefile.tanka

https://mintel.atlassian.net/browse/CPT-1156

Fix the k8s/tanka/generate/${APP_NAME} target

---

modules/k8s/tanka/new-app.sh

Brings in line with the `m` notation people now favour.

Notation and shellcheck updates for new-app.sh

---

README.md
modules/sentinel/Makefile

Add sentinel support

---

modules/k8s/tanka/new-app.sh

Will give developers a list of namespaces to choose from OR give them the opportunity to enter one manually.

Added namespace picker

---

modules/grafana/Makefile

Allow macs to work with this :green_apple:

Update make grafana/develop module to remove the unit on sleep

---

modules/grafana/Makefile

Upgrade grafana local dev image to v9.3.0

---

modules/satoshi/k8s-tool-versions

Adds alertmanager `amtool` via asdf.

Adding alertmanager amtool to asdf

---

modules/grafana/Makefile

- Bump grafana image version
- Enable traceql-editor tab for tempo

Bump grafana settings to match our prod setup

---

.github/workflows/renovate.yml

Fix the renovate github action version, and allow the action to be run manually.

Fix renovate

---

modules/grafana/Makefile

We make use of some extra plugins, so install them

INFRA-30830: Install extra grafana plugins used in local dev

---

modules/grafana/Makefile

This will come in handy to populate variables from our constants.git repo.

INFRA-30531: Adding grafana datasource plugin to query json api endpoints

---

modules/satoshi/tf-tool-versions

Upgrade to the latest tool versions.

Update Terraform tool versions

---

modules/satoshi/packer-makefile.template

- fix: add packer to help filter and remove non-relevant bits

Packer helpers

---

.github/workflows/asdf.yml
.github/workflows/linter.yml
.github/workflows/renovate.yml

Update the versions, and also increase the timeout for the renovatebot job.

Update GitHub actions
