README.md, modules/jsonnet/Makefile
Without this it's pretty difficult to re-generate golden tests, for example when a dep. changes.
This just provides a `jsonnet/rm-golden` target that can be used to delete old golden tests, so that `jsonnet/gen-golden` re-creates all tests.
Also removed old `parse` target (not used) and added `PHONY`
=> Clean golden tests before re-generating them.

modules/kind/Makefile
This enables `kind/create` to show up when we run `make help` in build-harness.
=> Added required comment for `kind/create`

modules/jsonnet/Makefile
causing the pipeline jobs to succed on gitlab even though they actually failed
https://gitlab.com/mintel/satoshi/kubernetes/jsonnet/sre/kube-monitoring-jsonnet/-/jobs/877225097
=> When in a for loop the error won't propagate

modules/tanka/Makefile
- Return non-zero if formatting is required (can be used by CI).
- `tanka/fmt` never returns non-zero
=> Added 'tanka/fmt-test' 

modules/tanka/generate.sh
When testing jsonnet code locally we typically us `tk apply`, so there's no need to render and commit the local versions of Kubernetes manifests.
=> tanka: Don't render local env by default

modules/kubeval/Makefile, modules/pluto/Makefile, modules/satoshi/makefile.template, modules/satoshi/tool-versions
- Update makefile help to show k3d instead of kind
- Update `.tool-versions` (all are compatible)
- Update default k8s versions for pluto/kubeval k8s validation tools
=> Bump satoshi deps

modules/pluto/Makefile
By setting this flag, we run can multiple granular validate jobs in the CI
pipeline to check multiple versions of K8s with optional failure.
=> Set --ignore-deprecations for pluto/validate target

modules/asdf/Makefile, modules/satoshi/tool-versions
Google has a newer implementation of jsonnet, written (mostly) in Go:
https://github.com/google/go-jsonnet
It's compatible with the original jsonnet, has a few additional
features, and is "orders of magnitude faster [in some cases]."
This PR also changes how asdf plugins are added; the `asdf/install` target will now look for comments formatted like this:
```
#asdf:plugin add go-jsonnet https://github.com/sirikon/asdf-go-jsonnet.git
```
Everything after `#asdf:` is called as an asdf subcommand.
=> Prefer go-jsonnet to jsonnet

modules/asdf/Makefile
1. It doesn't actually do the install.
2. Need to ignore errors from `asdf plugin add` when the plugin has already been added.
=> Fix asdf install

.github/workflows/linter.yml
https://mintel.atlassian.net/browse/CPT-445
Adds a workflow to lint bash scripts during pull requests.  Comments will be added to the PR in the event that any errors are found.
=> CPT-445 -- Add linting worflow

modules/k8s/tanka/generate.sh
Setting a deprecation trace message in the upstream libs-jsonnet repo results in a ton of trace messages from the `tk env list` command. We can send them to `/dev/null` and still be able to see them in the `tk export` output.
=> send tk env list errors to /dev/null

modules/k8s/tanka/generate.sh, modules/k8s/tanka/new-app.sh
This changes the Tanka manifest generation script to filter by 'app' and  'env' labels, which is more reliable than the current grep implementation. Grep is having some problems when envs have similar names e.g. `aws.dev` vs `aws.dev.bb1`.
I will use https://github.com/lindell/multi-gitter to open MRs to add labels to all the existing jsonnet repos.
=> Filter Tanka Environments by label instead of by grep

modules/grafana/Makefile, modules/grafana/scripts/local_dashboard_directory_prompt.sh
`make grafana/develop` now prompts the user for the relative path to the dashboards directory if the `LOCAL_DASHBOARD_DIRECTORY` env variable is not explicitly set
=> Added grafana/develop prompt to ask for dashboards directory if not specified

README.md, modules/satoshi/k8s-makefile.template, modules/satoshi/tf-makefile.template
https://github.blog/changelog/2022-04-25-git-io-deprecation/
Git.io now returns redirects which curl doesn't follow.
=> Replace git.io URLs

modules/grafana/Makefile
- Added `CREATE_GRAFANA_INSTANCE` flag to `make grafana/develop`. Set to false if you already have a grafana instance on `localhost:3000` and don't want to overwrite it with a fresh one.
- Updated `make grafana/develop` to pull the latest docker images before running.
=> [CPT-1063] Added create grafana flag to grafana/develop

modules/k8s/Makefile.tanka, modules/k8s/tanka/generate.sh
Fixes an issue where the args would sometimes be passed into the script in the wrong place if, for instance, `env` was defined but `app` was not.
=> Fix tanka/generate args

modules/grafana/Makefile
The docker image `grafana/grafana:latest` includes beta versions which
we don't want. Pin the Grafana image to the version we actually have
deployed.
=> Pin grafana image version

modules/k8s/tanka/generate.sh, modules/satoshi/k8s-tool-versions
Tanka can render multiple manifests in parallel. It's just a matter of
convincing it to generate files at the paths we want. That's what this
commit does.
Timings for rendering all of core-cluster-jsonnet:
- Before: 112.84 secs
- After: 38.02 seconds
Note: this change also removes the manifest.json files under
`rendered/`. I don't think they're used for anything.
=> Render manifests in parallel

modules/argocd/Makefile
this fixes the issue of removing the temporary `bin/` directory failing
=> fix cleanup for updater/test target

modules/k8s/Makefile.kubecfg
The core-cluster-jsonnet pipeline is really slow; I want it to be
faster.
This commit will allow us to parallelize kubecfg validation by running
something like `make -j64 k8s/kubecfg/validate`... although this change will
probably make the bare `make k8s/kubecfg/validate` slower because it has to
spend more time stopping and starting kubecfg.
=> Run kubecfg validate as Makefile targets

modules/grafana/Makefile
- Mount the users `.aws` home directory into grafana so we can have datasources assume role
- Pass in the `AWS_PROFILE` (needed) 
- Run with local user-id (allows grafana to read the `./aws/sso/cache/.*` files (these are `ro` only the the owner...)
- Avoid needing to login with admin user
=> CPT 1539: Grafana dashboard tooling updates

modules/k8s/Makefile.tanka
Some charts include `.gitignore` files in their charts so to counteract this we force the `make tanka/generate` command to run a `tk tool charts vendor` with the option to `rm` the directory beforehand ensuring that it is downloaded again from scratch (using the ALWAYS_VENDOR_CHARTS environment variable). This ensures that the CI pipeline has all the chart files it needs.
=> Add charts vendoring to `make tanka/generate`

modules/pipenv/Makefile
If `pipenv` is not installed defining this env at the top-level breaks (moving to target provides a bit more protection)
=> Fix check for Pipfile location 

modules/python/Makefile.flake8
it's useful to have flake8 return the exit code (rather than always forcing it to zero)
I was considering replacing this with an optional `FLAKE8_EXTRA_FLAGS` ...but if it's really required can we just supply `FLAKE8_FLAGS` instead.
=> Remove exit-zero from flake8 flags (it's useful)

modules/k8s/local/k3d.sh
Helm can grab the default namespace from the CI's auto-mounted service-account creds.
```
/var/run/secrets/kubernetes.io/serviceaccount/namespace
```
https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#directly-accessing-the-rest-api
In this case we run our CI inside k8s, so this `namespace` for the CI build pod is currently set to the namespace that the CI Deployment runs in  (which is not `default`).
That namespace will not exists in the k3d install..so it won't work :)
---
A workaround is to set the namespace when running Helm. 
More than that though, we don't need a couple of tasks to run in CI, so I've disabled them entirely.
=> INFRA 28193: Fix helm and secrets usage in CI (when run in k8s)

modules/k8s/tanka/generate.sh
If we delete an environment the existing script would not have removed the rendered manifests.
This would then fail the CI.
For example deleting an app or a whole environment should result in the rendered manifests being deleted too when `make tanka/generate` is called.
=> tanka/generate: Remove dangling rendered directories

modules/satoshi/tf-tool-versions
- Running the `make satoshi/update-tools` command without the `/tf` suffix pulls the jsonnet file rather than the terraform one
- The instructions to update the tfc-agent image are no longer necessary
=> Fix comments on tf-tool-versions file

modules/asdf/Makefile
Adds the following message after installing  asdf:
```
Profile changes are required. Add the following to your .bashrc:
if [ -e /path/to/home/.asdf ]; then
. /path/to/home/.asdf/asdf.sh
. /path/to/home/.asdf/completions/asdf.bash
fi
Or see https://asdf-vm.com/guide/getting-started.html#_3-install-asdf for details
```
=> Add instructions to asdf install

modules/k8s/tanka/generate.sh
Tanka is printing warnings like:
> Flag --merge has been deprecated, use --merge-strategy=fail-on-conflicts instead
We might want to look at the new features of this flag later; it might
replace some of the bash scripting we've written.
https://tanka.dev/exporting#partial-export-in-a-gitops-context
=> Fix Tanka deprecated flag warning

modules/satoshi/Makefile
We attempt to print some pretty colors in a few places of our build-harness-extensions. However, if these Makefiles are being used in a non-tty environment (such as renovate's postUpdateTasks) the `tput` command will fail with an error, causing the whole make command to fail. This commit falls back to ordinary, unformatted text when TERM is not set or unknown.
=> Fix crash due to terminal colors with no terminal

modules/satoshi/Makefile
When we run a Makefile command like `make satoshi/update-makefile/k8s`, we want Make to always update the target file. Normally you would do this by adding your target to `.PHONY: <mytarget>`.
See: https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
But `.PHONY` doesn't support pattern rules like
`satoshi/update-makefile/%s`. We need to do something different to force those to always run.
See: https://www.gnu.org/software/make/manual/html_node/Force-Targets.html
=> Force update-makefile and update-tools to run

modules/k8s/tanka/generate.sh
I ran into a situation where an environment variable named `ENV` had already been set in a CI pipeline, and it messed with the Tanka manifest rendering script. This commit makes the variable names in that script more specific.
=> Fix env var name conflict in Tanka render script

modules/kyverno/Makefile, modules/satoshi/k8s-makefile.template, modules/satoshi/k8s-tool-versions
This commit adds a Makefile target for testing our current set of Kyverno policies against jsonnet repo rendered manifests. It is not currently aware of any PolicyExceptions we set up, so it isn't currently suitable for adding to our CI pipeline.
=> Add kyverno/test target

modules/satoshi/k8s-tool-versions
Newer versions of the conftest plugin for asdf don't seem to like the version number being prefixed with a `v`. It results in trying to download a URL like:
https://github.com/open-policy-agent/conftest/releases/download/vv0.39.2/conftest_v0.39.2_Linux_x86_64.tar.gz
Note the double `vv`.
=> Remove v from conftest version

modules/k8s/local/create-ns.sh
In some cases, such as namespace-jsonnet, we have apps that output manifests across multiple namespaces. Therefore, when creating namespaces in a local cluster, we can't always rely on the namespace specified in the Tanka environment file.
Change the `make k8s/local/create-ns` target to extract the namespace names from the rendered manifests instead.
=> Create local namespaces from rendered manifests

modules/grafana/Makefile
Reverts mintel/build-harness-extensions#159
Most likely not possible since the image runs as non-root and I can't mount aws-sso creds into this container in a usable manner :)
=> Revert "INFRA-30830: Use bitnami grafana image"

.github/renovate.json5
asdf is supposed to allow version numbers both like `1.2.3` and `v1.2.3`. However, the implementation is left up to the underlying plugin and they often don't get it right, resulting in asdf trying to download from URLs like
`https://github.com/blah/blah/releases/vv1.2.3/my-tool-x86_64`.
This commit will instruct renovatebot to write version numbers like `1.2.3`, but also allows us to override it on a per-tool basis to write version numbers like `v1.2.3` if the underlying plugin needs them to be written that way.
=> Fix asdf renovatebot config

modules/satoshi/k8s-tool-versions
I need the OCI Helm chart support that was added in v0.25.0.
=> Upgrade tanka to v0.26.0

modules/k8s/Makefile.tanka
The Fusion >=5.6.0 Helm charts have an issue that prevents them from being rendered before they are even passed into the Jsonnet bit. This means we can’t monkey patch manifests with Jsonnet in the usual way and the charts are closed source so we can’t change them upstream.
We’ve raised a request with Lucidworks to fix this but in the meantime we need better support for patching the files downloaded to the `charts/` directory.
=> INFRA-32499: Add pre-rendering Helm chart patching support to Tanka repos

modules/k8s/Makefile.tanka
`patch` will always run when a patch is found and it will exit with code 1 if it skips a file because it has already been patched. Exit code 2 is for "more serious" issues according to `man patch` so we'll ignore 1s and exit on >1s.
=> Fix repatching attempts

modules/satoshi/tf-tool-versions
Required for providerless modules with "entrypoint" submodules
=> Add gomplate and hcl2json to terraform tool-versions

modules/grafana/Makefile, modules/grafana/env.list, modules/grafana/scripts/datasource_credentials.sh, modules/grafana/scripts/patch_datasources.sh
This commit removes the need for the build-harness-extensions-private repo. Instead, the grafana-operator manifests will be fetched from core-cluster-jsonnet and patched by `yq` to perform local dashboard development.
Additionally, if you are developing dashboards in core-cluster-jsonnet, it won't checkout a second core-cluster-jsonnet repo to get the grafana-operator manifests. This opens up options for testing changes to our datasources locally.
=> Use Grafana datasources from core-cluster-jsonnet for local dev

modules/opa/Makefile
This allows us (via CI or whatever) to override `OPA_POLICY_SUBDIR` and supply a specific directory of checks (or single check).
We also include the `utils.rego` which is nearly always required - it would fail if you supplied a custom subdir since utils.rego would not be in the path.
=> Support custom policy-subdir for opa (conftest) tests

modules/opa/Makefile
Pass in application validation data to `conftest` - it no longer exists within the policy repo itself.
Also update `OPA_POLICY_DIR` to use the branch name as well (a bit safer).
=> INFRA-37285: Update conftest to parse in application validation data

modules/opa/Makefile
Accessing constants can fail, so handle it with a curl-retry. This cannot be used with redirects, so write to a file and then parse with `yq` as previous.
Also fix a small typo when cloning the opa repo.
=> INFRA-37285: Handle errors when fetching constants

modules/kyverno/Makefile, modules/satoshi/k8s-tool-versions
This MR requires the latest version of kyverno-cli (tested against 1.13.4)
It allows `make kyverno/test` to be run locally (and in CI), without the need for deploying a k3d/kind cluster (so speeds up jobs).
`kyverno-cli` now supports passing through `--exceptions` which means this helper can be run locally.
The change is:
1. Patch `ClusterPolicy` manifests to remove the `.metadata.namespace` field. This is an issue with how we generated the rendered manifests with Tanka. This previously was not an issue as the tests were run in a k8s cluster. It's an issue now as the policies do not match as they are namespaced (probably a bug in kyverno...)
3. Combine yaml where required to avoid the need for extra loops
4. Update `kyverno apply` to pass in `--exceptions` and also configure the output to …
=> Infra 39554: Update `make kyverno/test` to use PolicyExceptions

modules/grafana/Makefile
Fixes permission issues. The user-id passed in was blank previously (or not set at all in the case of the syncer).
=> INFRA-40823: Fix grafana-syncer permissions issue specifying
